eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
server:
  port: 8080
  
spring:
  application:
    name: springgateway
 
  cloud:
    gateway:
      routes:
      - id: firstservice
        uri: lb://firstservice
        predicates:
        - Path=/firstservice/**
      - id: secondservice
        uri: lb://SECONDSERVICE
        predicates:
        - Path=/secondservice/**

